version: '3'

services:
  db:
    restart: always
    image: postgres:12-alpine
    container_name: fs-mng-backend-db-container
    ports:
      - "19999:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpass
      - PGPASSWORD=localpass
      - POSTGRES_DB=backenddb
      - DATABASE_HOST=localhost
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d/
