// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Node interface {
	IsNode()
}

type Movie struct {
	// UUID
	ID string `json:"id"`
	// 名称
	Name string `json:"name"`
	// 動画URL
	MovieURL string `json:"movieUrl"`
	// 秒数
	Scale int `json:"scale"`
}

func (Movie) IsNode() {}

type MovieInput struct {
	// 名称
	Name string `json:"name"`
	// 動画URL
	MovieFile graphql.Upload `json:"movieFile"`
	// 秒数
	Scale int `json:"scale"`
}

type MutationResponse struct {
	ID *string `json:"id"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
