// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

// 組織
type Organization struct {
	// UUID
	ID string `json:"id"`
	// 名称
	Name string `json:"Name"`
	// 上位組織
	UpperOrganization *Organization `json:"upperOrganization"`
	// 下位組織群
	LowerOrganizations []*Organization `json:"lowerOrganizations"`
}

func (Organization) IsNode() {}

// 組織検索条件
type OrganizationCondition struct {
	// UUID
	ID *string `json:"id"`
	// 名称
	Name string `json:"Name"`
}

// 組織入力情報
type OrganizationInput struct {
	// UUID
	ID *string `json:"id"`
	// 名称
	Name string `json:"Name"`
	// 上位組織ID
	UpperOrganizationID *string `json:"upperOrganizationId"`
	// 下位組織ID群
	LowerOrganizationsIds []*string `json:"lowerOrganizationsIds"`
}

// 作品
type Work struct {
	// UUID
	ID string `json:"id"`
	// 作品名
	Name string `json:"name"`
	// 価格（無料は0円）
	Price int `json:"price"`
	// 作成者群（不明な場合もある）
	WorkHolders []*WorkHolder `json:"workHolders"`
}

func (Work) IsNode() {}

// 作品検索条件
type WorkCondition struct {
	// UUID
	ID *string `json:"id"`
	// 作品名
	Name *string `json:"name"`
	// 価格（無料は0円）
	Price *int `json:"price"`
	// 作成者ID
	WorkHolderID *string `json:"workHolderId"`
}

// 作成者
type WorkHolder struct {
	// UUID
	ID string `json:"id"`
	// 姓
	FirstName string `json:"firstName"`
	// 名
	LastName string `json:"lastName"`
	// ニックネーム
	Nickname *string `json:"nickname"`
	// 所属組織群
	Organizations []*Organization `json:"organizations"`
	// 所持作品群
	HoldWorks []*Work `json:"holdWorks"`
}

func (WorkHolder) IsNode() {}

// 作成者検索条件
type WorkHolderCondition struct {
	// UUID
	ID *string `json:"id"`
	// 姓
	FirstName *string `json:"firstName"`
	// 名
	LastName *string `json:"lastName"`
	// ニックネーム
	Nickname *string `json:"nickname"`
	// 所属組織ID
	OrganizationID *string `json:"organizationId"`
}

// 作成者入力情報
type WorkHolderInput struct {
	// UUID
	ID *string `json:"id"`
	// 姓
	FirstName string `json:"firstName"`
	// 名
	LastName string `json:"lastName"`
	// ニックネーム
	Nickname *string `json:"nickname"`
	// 所属組織ID群（※必ずしも所属する必要はない）
	OrganizationIds []*string `json:"organizationIds"`
}

// 作品入力情報
type WorkInput struct {
	// UUID
	ID *string `json:"id"`
	// 作品名
	Name string `json:"name"`
	// 価格（無料は0円）
	Price int `json:"price"`
	// 作成者ID群
	ItemHolderIds []*string `json:"itemHolderIds"`
}
