// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Organization       string
	Work               string
	WorkHolder         string
	WorkHolderRelation string
}{
	Organization:       "organization",
	Work:               "work",
	WorkHolder:         "work_holder",
	WorkHolderRelation: "work_holder_relation",
}
